# sudo docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db docker.uclv.cu/mongo

version: "2.6"

services:
  mongo:
    image: docker.uclv.cu/mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: docker.uclv.cu/rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata: